openapi: 3.0.3

info:
  title: API de Gesti贸n Escolar
  version: 1.0.0
  description: >
    Documentaci贸n de la API del sistema escolar con autenticaci贸n por Cookie HttpOnly,
    gesti贸n de usuarios, profesores, asignaturas, consultas y evaluaciones.

servers:
  - url: http://localhost:3000
    description: Servidor local

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token

security:
  - cookieAuth: []

tags:
  - name: Autenticaci贸n
    description: Endpoints relacionados con login y sesi贸n.
  - name: Profesores
    description: Gesti贸n completa de profesores.
  - name: Usuarios
    description: Administraci贸n de usuarios del sistema.
  - name: Asignaturas
    description: Gesti贸n de materias o asignaturas.
  - name: Consultas
    description: Registro y control de consultas.
  - name: Evaluaciones
    description: Evaluaciones realizadas a profesores.

paths:

  #######################################
  #  1. AUTENTICACIN
  #######################################

  /api/auth/login:
    get:
      tags: [Autenticaci贸n]
      summary: Obtener datos del usuario autenticado
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Usuario autenticado
          content:
            application/json:
              example:
                usuario: "Juan P茅rez"
                rol: "admin"
                token: "jwt"
        "401":
          description: No autenticado

  #######################################
  #  2. PROFESORES
  #######################################

  /api/profesores:
    get:
      tags: [Profesores]
      summary: Obtener profesores
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Lista de profesores

    post:
      tags: [Profesores]
      summary: Crear profesor
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [nombre, correo, telefono, estatus]
              properties:
                nombre:
                  type: string
                correo:
                  type: string
                telefono:
                  type: string
                estatus:
                  type: string
      responses:
        "201":
          description: Profesor creado

  /api/profesores/{codigo}:
    put:
      tags: [Profesores]
      summary: Actualizar profesor
      security:
        - cookieAuth: []
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                telefono:
                  type: string
                estatus:
                  type: string
      responses:
        "200":
          description: Profesor actualizado
        "404":
          description: No encontrado

    delete:
      tags: [Profesores]
      summary: Eliminar profesor
      security:
        - cookieAuth: []
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Profesor eliminado

  #######################################
  #  3. USUARIOS
  #######################################

  /api/usuarios:
    get:
      tags: [Usuarios]
      summary: Obtener usuarios
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Lista de usuarios

    post:
      tags: [Usuarios]
      summary: Crear usuario
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [nombre, correo, rol, contrasena]
              properties:
                nombre:
                  type: string
                correo:
                  type: string
                rol:
                  type: string
                contrasena:
                  type: string
      responses:
        "201":
          description: Usuario creado

  /api/usuarios/{codigo}:
    put:
      tags: [Usuarios]
      summary: Actualizar usuario
      security:
        - cookieAuth: []
      parameters:
        - name: codigo
          required: true
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                telefono:
                  type: string
                estatus:
                  type: string
      responses:
        "200":
          description: Usuario actualizado

    delete:
      tags: [Usuarios]
      summary: Eliminar usuario
      security:
        - cookieAuth: []
      parameters:
        - name: codigo
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: Usuario eliminado

  #######################################
  #  4. ASIGNATURAS
  #######################################

  /api/asignaturas:
    get:
      tags: [Asignaturas]
      summary: Obtener asignaturas
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Lista de asignaturas

    post:
      tags: [Asignaturas]
      summary: Crear asignatura
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [nombre, codigo, descripcion]
              properties:
                nombre:
                  type: string
                codigo:
                  type: string
                descripcion:
                  type: string
      responses:
        "201":
          description: Asignatura creada

  /api/asignaturas/{codigo}:
    put:
      tags: [Asignaturas]
      summary: Actualizar asignatura
      security:
        - cookieAuth: []
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                codigo:
                  type: string
                descripcion:
                  type: string
      responses:
        "200":
          description: Asignatura actualizada

    delete:
      tags: [Asignaturas]
      summary: Eliminar asignatura
      security:
        - cookieAuth: []
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Asignatura eliminada

  #######################################
  #  5. CONSULTAS
  #######################################

  /api/consultas:
    get:
      tags: [Consultas]
      summary: Obtener consultas
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Lista de consultas

    post:
      tags: [Consultas]
      summary: Crear consulta
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [idProfesor, idAsignatura, estatus, fecha]
              properties:
                idProfesor:
                  type: string
                idAsignatura:
                  type: string
                estatus:
                  type: string
                fecha:
                  type: string
      responses:
        "201":
          description: Consulta creada

  /api/consultas/{codigo}:
    put:
      tags: [Consultas]
      summary: Actualizar consulta
      security:
        - cookieAuth: []
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                idProfesor:
                  type: string
                idAsignatura:
                  type: string
                estatus:
                  type: string
                fecha:
                  type: string
      responses:
        "200":
          description: Consulta actualizada

    delete:
      tags: [Consultas]
      summary: Eliminar consulta
      security:
        - cookieAuth: []
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Consulta eliminada

  #######################################
  #  6. EVALUACIONES
  #######################################

  /api/evaluaciones:
    get:
      tags: [Evaluaciones]
      summary: Obtener evaluaciones
      security:
        - cookieAuth: []
      responses:
        "200":
          description: Lista de evaluaciones

    post:
      tags: [Evaluaciones]
      summary: Crear evaluaci贸n
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [profesor, asignatura, calificacion, observaciones]
              properties:
                profesor:
                  type: string
                asignatura:
                  type: string
                calificacion:
                  type: number
                observaciones:
                  type: string
      responses:
        "201":
          description: Evaluaci贸n creada

  /api/evaluaciones/{codigo}:
    put:
      tags: [Evaluaciones]
      summary: Actualizar evaluaci贸n
      security:
        - cookieAuth: []
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                profesor:
                  type: string
                asignatura:
                  type: string
                calificacion:
                  type: number
                observaciones:
                  type: string
      responses:
        "200":
          description: Evaluaci贸n actualizada

    delete:
      tags: [Evaluaciones]
      summary: Eliminar evaluaci贸n
      security:
        - cookieAuth: []
      parameters:
        - name: codigo
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Evaluaci贸n eliminada
